site_name: OhMyZsh
site_url: https://simplon-hdf.github.io/cheatsheet-ohmyzsh-p5/
theme: 
    name: terminal
    palette: dark
nav:
  - Installation: installation.md
  - Plugins: plugin.md
  - Themes: theme.md
  - Paramètres: settings.md
